[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "market-simulation"
version = "0.0.1"
description = "MarS market simulation"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pandas==2.2.3",
    "numpy",
    "matplotlib",
    "seaborn==0.13.2",
    "scipy==1.15.2",
    "tqdm",
    "ruamel.yaml==0.18.6",
    "pydantic==2.10.3",
    "pydantic-settings==2.8.1",
    "python-dotenv==1.0.1",
    "rich==13.9.4",
    "zstandard==0.23.0",
    "ray[serve]==2.44.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "transformers==4.50.0",
    "streamlit==1.40.1",
]

[project.optional-dependencies]
dev = [
    "mypy==1.15.0",
    "pre-commit==4.2.0",
    "types-protobuf==5.29.1.20250315",
    "types-requests==2.32.0.20250306",
    "tqdm-stubs==0.2.1",
    "ipython==9.0.2",
    "ruff==0.11.2",
    "pandas-stubs==2.2.3.250308",
]
train = [
    "lightning",
    "pyarrow",
    "zarr",
    "numcodecs",
    "datasets",
    "omegaconf",
    "pysindy",
]

[tool.setuptools]
packages = ["market_simulation", "mlib", "custom_code"]

[tool.pyright]
reportGeneralTypeIssues = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
ignore = [".git", ".eggs", "tmp"]

[tool.mypy]
exclude = [".git", ".eggs", "tmp"]
ignore_missing_imports = true

[tool.ruff]
unsafe-fixes = true
line-length = 150
indent-width = 4
target-version = "py312"
exclude = [".git", ".eggs", "tmp"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D403","D415","D100","ANN401","S301","RET504","BLE001","G004","ERA001",
    "D104","ISC001","COM812","TD003","FIX002","PIE790","S101","D107","EM101",
    "SIM108","TRY003","D105","PGH003","SIM103","EM102","PLR2004","PT018",
    "PLR1711","RET501","RUF015","S311","C901","PLR0912","NPY002","DTZ001",
    "S113","PERF401","S105","FA100","TRY300","LOG015","ARG002","A002","A001",
]

[tool.ruff.lint.pylint]
max-args = 15
max-branches = 20
max-returns = 15

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.pydocstyle]
convention = "google"