wandb_version: 1

batch_size:
  value: 8
eval_every:
  value: 100
lr:
  value: 0.0003
max_steps:
  value: 20000
model_variant:
  value: base
seed:
  value: 123
train_fraction:
  value: 1
val_max_batches:
  value: 200
