_wandb:
    value:
        cli_version: 0.23.1
        e:
            hujeia8i6izbvp66ae0kbco1yrdjf7j9:
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: aymeric.barbin@gmail.com
                executable: /PUHTI_TYKKY_Quvj2Tb/miniforge/envs/env1/bin/python
                git:
                    commit: 26b9678e37f4deb0a3427ffaddf885e6df18f337
                    remote: https://github.com/TUNI-Financial-Computing/MarS.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-37d5a490-044b-e3b4-6336-cec308b199e8
                host: r01g03.bullx
                memory:
                    total: "403794300928"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: mars_order_model_sweep
                python: CPython 3.12.12
                root: /projappl/project_2012747/mars/MarS/custom_code
                slurm:
                    cluster_name: puhti
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "10"
                    cpus_per_task: "10"
                    export_env: NONE
                    get_user_env: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    hint: nomultithread
                    job_account: project_2012747
                    job_cpus_per_node: "10"
                    job_end_time: "1768348854"
                    job_gid: "10031943"
                    job_gpus: "1"
                    job_id: "31170337"
                    job_name: sys/dashboard/sys/ood-base-jupyter
                    job_nodelist: r01g03
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1768320054"
                    job_uid: "10031943"
                    job_user: pst
                    jobid: "31170337"
                    localid: "0"
                    mem_per_node: "49152"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: r01g03
                    ood_env: prod
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /var/www/ood/apps/sys/dashboard
                    submit_host: puhti-ood-production.csc.fi
                    task_pid: "3369759"
                    tasks_per_node: "1"
                    threads_per_core: "1"
                    topology_addr: r01g03
                    topology_addr_pattern: node
                    tres_per_task: cpu=10
                startedAt: "2026-01-13T16:03:24.266176Z"
                writerId: hujeia8i6izbvp66ae0kbco1yrdjf7j9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
            "3":
                - 2
                - 14
                - 61
                - 62
            "4": 3.12.12
            "5": 0.23.1
            "6": 4.50.0
            "8":
                - 1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 8
emb_dim:
    value: 64
eval_every:
    value: 50
lr:
    value: 0.0003
max_steps:
    value: 2000
model_variant:
    value: base
n_params:
    value: 10179648
num_heads:
    value: 4
num_layers:
    value: 2
seed:
    value: 123
train_fraction:
    value: 1
val_max_batches:
    value: 200
